import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import KudoFab from "@/app/_components/shared/kudo-fab";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 7-segment LCD font for the /prelaunch countdown digits.
// Renders ghost unlit segments — matches the Figma "Digital Numbers" look.
const dseg7 = localFont({
  src: "../public/fonts/DSEG7Classic-Bold.woff2",
  variable: "--font-dseg7",
  display: "swap",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${dseg7.variable} h-full antialiased`}
    >
      <head>
        {/* Montserrat — the design-system font referenced across the app
            (fontFamily: "Montserrat"). Montserrat Alternates backs the footer
            copyright line (Figma uses it). Loaded here so those references
            resolve instead of falling back to Arial / plain Montserrat. */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&family=Montserrat+Alternates:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        {/* Shared floating Viết Kudo button — rendered once for every route;
            self-gates to logged-in users (renders null otherwise). */}
        <KudoFab />
      </body>
    </html>
  );
}
